### ISSUE TITLE
Rails 5 renderer instead of integration test hack?

### ISSUE THREAD

**Issue by swrobel** [mvcodeclub/delayed_action#8]
Have you looked into using this new feature in Rails 5 to handle the rendering? https://evilmartians.com/chronicles/new-feature-in-rails-5-render-views-outside-of-actions

**Comment by tarr11** [comment]
Seems like it would be fairly straightforward to swap this in, but not sure if it adds much value?

Feel free to create a PR for it though!

**Comment by swrobel** [comment]
In playing with it, I discovered it doesn't behave as expected. It doesn't actually seem to run the controller action, it just renders the view. You have to generate & pass in all of the locals to the view.
